# Generated by Django 5.1 on 2024-08-10 11:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,10}$",
                                "Only numeric characters are allowed and the length must be 10 digits or fewer.",
                            )
                        ],
                    ),
                ),
                ("email", models.CharField(max_length=40)),
                ("Location", models.CharField(max_length=70)),
                ("story", models.CharField(max_length=200)),
                ("InterestSpecial", models.CharField(max_length=200)),
                ("projectdevelop", models.CharField(max_length=200)),
                ("tooldevelop", models.CharField(max_length=200)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
