# Generated by Django 5.1 on 2024-08-10 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Profile",
        ),
    ]
